# Generated by Django 4.2.4 on 2024-04-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
    ]
